### PR TITLE
added style for snackbar

### PR DESCRIPTION
**Pull request by aishwarya-bm**
added style for snackbar
snackbar

### CODE REVIEW

**Review by sadathshariff — COMMENTED** [review]
Looks good to merge, you can add some more variants

**Review by krishanu2911 — COMMENTED** [review]
Everything seems good to go no changes are required according to me

**Review by anushasunil — COMMENTED** [review]
Just a suggestion, try changing the color for "RETRY" and close icon into a lighter shade.
Rest everything looks good.

**Comment by aishwarya-bm** [comment]
> Looks good to merge, you can add some more variants

In the interest of time I have added only the basic style

**Comment by aishwarya-bm** [comment]
> Just a suggestion, try changing the color for "RETRY" and close icon into a lighter shade. Rest everything looks good.

Made changes

**Review by anushasunil — APPROVED** [review]

**Pull request merged**
